# Generated by Django 4.2.4 on 2023-12-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='client_name',
        ),
        migrations.AddField(
            model_name='message',
            name='client_email',
            field=models.EmailField(default='zitsmartengineer@gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_id',
            field=models.IntegerField(default=1),
        ),
    ]
