# Generated by Django 4.2.4 on 2023-12-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_message_client_name_message_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='letter',
            field=models.CharField(max_length=500),
        ),
    ]
