# Generated by Django 4.2.4 on 2023-12-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_message_letter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='client_email',
            new_name='sender_email',
        ),
    ]
