# Generated by Django 4.2.4 on 2023-12-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
