# Generated by Django 4.2.4 on 2023-12-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
